### PR TITLE
Hide additional minute markers while animating

### PR DESCRIPTION
**Pull request by Martijn02**
Don't show the additional minute markers until the animation has finished.

### CODE REVIEW

**Comment by silasg** [comment]
Thanks for your pull request. I'm a little busy right now but I'll release it as soon as possible after some testing ;)

**Comment by Martijn02** [comment]
Sorry, I did not intend to include the "Made seconds hand show up for 30 secs on tap/shake" in this pull request. It still needs a change to the configuration page in order to turn the feature on. If you want I can add that change as well. 

The feature works surprisingly well though. I have it on my pebble for 2 weeks now. There is no noticeable battery drain.

**Comment by silasg** [comment]
Hi Martin,

yes, I’ve seen it, no worries. I thought about migrating to Clay offline config (https://github.com/pebble/clay) for the next release, so you don’t need to spend the time to update the old configuration page.

Features is working for me for about a week now, too. The only thing I encountered is, that after shaking it takes about one second to display the seconds hand. I’ll have a look, if this could somehow speeded up, maybe by forcing a screen update directly somehow.

Best,

Silas

**Comment by Martijn02** [comment]
Hi Silas,

I noticed the same behavior and I tried that too, I tried doing a `layer_mark_dirty(s_canvas_layer);` in the `accel_tap_handler()` function. That triggers a direct redraw. Only problem is that the location of the second hand is not defined, to it shows pointing up to the 12 marker. Only after the next `tick_handler()` invocation by the timer, you have the correct time in `tick_time` to calculate the position of the seconds hand.

Maybe there is a better solution?

I also pondered adding a `s_draw_second_hand_tap_duration = HAND_SECONDS_TAP_DURATION;` to the `animation_started()` function. So that the seconds hand also shows for a while when you go back to the watch face from a menu or notification. Any thoughts about that?

Kind regards,

Martijn

**Comment by Martijn02** [comment]
This has a nice effect. Always shows the second hand during the animation. Fades it out before disappearing after 30 seconds.
https://github.com/Martijn02/thin-ext/commit/0c05fb1b826365b39fb397a9668922ecb78be0ca

**Comment by silasg** [comment]
Yes, looks nice. There was a small bug with the tip color, see my change for main window in https://github.com/silasg/thin-ext/commit/14b025d9f0e06654dda002f542856a7c344a1b35

I also changed the duration to show the seconds hand but I think this is a matter of personal preference.

Did you change anything regarding the delay before the hand is shown when tapping? I wonder if its faster now or if its just imagination ;)

**Pull request merged**
